language: c
sudo: false # only for faster builds
script:
  - cd test/
  - gcc -ILaboServ/unity -ILaboServ/modules -coverage -O0 -o main.o main.c
  - gcc -o LaboServ modules/LedDriver.o test/TestLedDriver.o test/main.o unity/unity.o unity/unity_fixture.o
  - ./main
  - gcov main.c
after_success:
  - bash <(curl -s https://codecov.io/bash)
# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
