language: c

matrix:
 include:
    - os: linux
      dist: trusty
      compiler: gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install --assume-yes --quiet gcc-multilib; fi
install: gem install rspec
script:
  - wget https://github.com/ThrowTheSwitch/Unity/archive/master.zip
  - unzip master.zip
  - cd Unity-master
  - cd test && rake ci
  - make -s
  - make -s DEBUG=-m32
  - cd ../extras/fixture/test && rake ci
  - make -s default noStdlibMalloc
  - make -s C89
  - cd ../../../examples/example_1 && make -s ci
  - cd ../example_2 && make -s ci
  - cd ../example_3 && rake
  - cd ../../../../test
  - gcc -I../unity -I../modules -coverage -O0 main.c -o main
  - ./main
  - gcov main.c
after_success:
  - bash <(curl -s https://codecov.io/bash)
# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
