language: c
sudo: false # only for faster builds
script:
  - cd test/
  - gcc -I../unity -I../modules -coverage -O0 -o main main.c
  - gcc -o modules/LedDriver test/TestLedDriver test/main unity/unity unity/unity_fixture
  - ./main
  - gcov main.c
after_success:
  - bash <(curl -s https://codecov.io/bash)
# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
